sonar.projectKey=dashboard
sonar.projectName=dashboard
sonar.projectVersion=1.0

sonar.sources=apps

sonar.tests=apps
sonar.test.inclusions=**/test/**/*.ts,**/test/**/*.tsx,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/.turbo/**,**/.vite/**,**/storybook-static/**,**/generated/**,**/drizzle/**/*.sql,**/*.d.ts
sonar.test.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/.turbo/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
