info:
  name: Get Pannels By projectId
  type: http
  seq: 2

http:
  method: GET
  url: "{{url}}/api/config/projects/f20rkqy3w59m3k5kloosbwug/panels?showDevelopmentPanel=true"
  params:
    - name: showDevelopmentPanel
      value: "true"
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
